# list, stack, pop (last in first out) ,remove, append, lenght,sort, 
i=[1,234,54,12,34,3,5,6,9844,554,31,3]
print(i)
print(len(i))
i.append(8)
print(i)
i.sort()
print(i)
i.append('khan')
print(i)
j=str(input('enter name '))
i.append(j)
print(i)
i.insert(8,0.111)
print(i)
i.remove(6)
print(i)
i.reverse()
print(i)
i.pop()
print(i)